import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'EMH-2/safety',
    'EMH-2/introduction',
    'EMH-2/quick-start',
    {
      type: 'category',
      label: 'Web Interface',
      collapsed: false,
      items: [
        'EMH-2/device',
        'EMH-2/strategy',
        'EMH-2/monitor',
        'EMH-2/system',
      ],
    },
    // 'EMH-2/integration',
    // 'EMH-2/tech-specs',
    // 'EMH-2/compatibility',
    // 'EMH-2/faq',
    // 'EMH-2/maintenance',
    // {
    //   type: 'category',
    //   label: 'Technical Support and Service',
    //   link: {type: 'doc', id: 'EMH-2/support'},
    //   items: [
    //     'EMH-2/glossary',
    //     'EMH-2/firmware',
    //   ],
    // },
  ],
  apiSidebar: [
    "API/OpenData"
  ],
};

export default sidebars;
